version: '3'
services:
  app:
    image: creatordashboard-server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://jacksoncheriyan05:T0DWV48UFszQg3rd@cluster0.azednih.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - CLIENT_URL=http://localhost:5173
      - JWT_SECRET=jwtsecret
      - NODE_ENV=development
      - REDDIT_CLIENT_ID=MKgEEtdN2M1NXnZn-VtVbA
      - REDDIT_REDIRECT_URI=http://localhost:5173/reddit-callback
      - REDDIT_CLIENT_SECRET=WmMnUn70iETFGkyZ-PdgKCENArgJyg