name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    
    - name: Build and deploy
      run: |
        # Set up environment for Docker build
        cp .env.production .env
        
        # Build and deploy
        gcloud auth configure-docker
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/creator-app .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/creator-app
        
        # Deploy with just the sensitive environment variables from GitHub Secrets
        gcloud run deploy creator-dashboard \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/creator-app \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars="MONGO_URI=${{ secrets.MONGO_URI }},JWT_SECRET=${{ secrets.JWT_SECRET }},REDDIT_CLIENT_SECRET=${{ secrets.REDDIT_CLIENT_SECRET }}"