name: Deploy to Cloud Run

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    
    - name: Build and deploy
      run: |
        gcloud auth configure-docker
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/creator-app .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/creator-app
        
        gcloud run deploy creator-dashboard \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/creator-app \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars="MONGO_URI=mongodb+srv://jacksoncheriyan05:T0DWV48UFszQg3rd@cluster0.azednih.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0,NODE_ENV=production,CLIENT_URL=http://localhost:5173,JWT_SECRET=jwtsecret,REDDIT_CLIENT_ID=MKgEEtdN2M1NXnZn-VtVbA,REDDIT_REDIRECT_URI=http://localhost:5173/reddit-callback,REDDIT_CLIENT_SECRET=WmMnUn70iETFGkyZ-PdgKCENArgJyg"