name: Deploy to Cloud Run

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    
    - name: Configure Docker
      run: gcloud auth configure-docker us-central1-docker.pkg.dev
    
    - name: Build and deploy
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/creator-repo/creator-app:latest .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/creator-repo/creator-app:latest
        
        gcloud run deploy creator-dashboard \
          --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/creator-repo/creator-app:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --cpu=1 \
          --memory=512Mi \
          --max-instances=10 \
          --set-env-vars="MONGO_URI=mongodb+srv://jacksoncheriyan05:T0DWV48UFszQg3rd@cluster0.azednih.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0,NODE_ENV=production,CLIENT_URL=http://localhost:5173,JWT_SECRET=jwtsecret,REDDIT_CLIENT_ID=MKgEEtdN2M1NXnZn-VtVbA,REDDIT_REDIRECT_URI=http://localhost:5173/reddit-callback,REDDIT_CLIENT_SECRET=WmMnUn70iETFGkyZ-PdgKCENArgJyg"